[package]
name = "ironbar-script-net"
version = "0.2.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
tokio = { version = "1.48.0", features = ["fs", "macros", "rt", "time"] }
tokio-stream = "0.1.17"
